const data = [
  {
    id: 0,
    no: 1,
    agent_travel: "John Doe",
    alamat: "2018/01/01",
    gambar: "Guest",
  },
  {
    id: 1,
    no: 1,
    agent_travel: "Samppa Nori",
    alamat: "2018/01/01",
    gambar: "Member",
  },
  {
    id: 2,
    no: 1,
    agent_travel: "Estavan Lykos",
    alamat: "2018/02/01",
    gambar: "Staff",
  },
  {
    id: 3,
    no: 1,
    agent_travel: "Chetan Mohamed",
    alamat: "2018/02/01",
    gambar: "Admin",
  },
  {
    id: 4,
    no: 1,
    agent_travel: "Derick Maximinus",
    alamat: "2018/03/01",
    gambar: "Member",
  },
  {
    id: 5,
    no: 1,
    agent_travel: "Friderik Dávid",
    alamat: "2018/01/21",
    gambar: "Staff",
  },
  {
    id: 6,
    no: 1,
    agent_travel: "Yiorgos Avraamu",
    alamat: "2018/01/01",
    gambar: "Member",
  },
  {
    id: 7,
    no: 1,
    agent_travel: "Avram Tarasios",
    alamat: "2018/02/01",
    gambar: "Staff",
  },
  {
    id: 8,
    no: 1,
    agent_travel: "Quintin Ed",
    alamat: "2018/02/01",
    gambar: "Admin",
  },
  {
    id: 9,
    no: 1,
    agent_travel: "Enéas Kwadwo",
    alamat: "2018/03/01",
    gambar: "Member",
  },
  {
    id: 10,
    no: 1,
    agent_travel: "Agapetus Tadeáš",
    alamat: "2018/01/21",
    gambar: "Staff",
  },
  {
    id: 11,
    no: 1,
    agent_travel: "Carwyn Fachtna",
    alamat: "2018/01/01",
    gambar: "Member",
  },
  {
    id: 12,
    no: 1,
    agent_travel: "Nehemiah Tatius",
    alamat: "2018/02/01",
    gambar: "Staff",
  },
  {
    id: 13,
    no: 1,
    agent_travel: "Ebbe Gemariah",
    alamat: "2018/02/01",
    gambar: "Admin",
  },
  {
    id: 14,
    no: 1,
    agent_travel: "Eustorgios Amulius",
    alamat: "2018/03/01",
    gambar: "Member",
  },
  {
    id: 15,
    no: 1,
    agent_travel: "Leopold Gáspár",
    alamat: "2018/01/21",
    gambar: "Staff",
  },
  {
    id: 16,
    no: 1,
    agent_travel: "Pompeius René",
    alamat: "2018/01/01",
    gambar: "Member",
  },
  {
    id: 17,
    no: 1,
    agent_travel: "Paĉjo Jadon",
    alamat: "2018/02/01",
    gambar: "Staff",
  },
  {
    id: 18,
    no: 1,
    agent_travel: "Micheal Mercurius",
    alamat: "2018/02/01",
    gambar: "Admin",
  },
  {
    id: 19,
    no: 1,
    agent_travel: "Ganesha Dubhghall",
    alamat: "2018/03/01",
    gambar: "Member",
  },
  {
    id: 20,
    no: 1,
    agent_travel: "Hiroto Šimun",
    alamat: "2018/01/21",
    gambar: "Staff",
  },
  {
    id: 21,
    no: 1,
    agent_travel: "Vishnu Serghei",
    alamat: "2018/01/01",
    gambar: "Member",
  },
  {
    id: 22,
    no: 1,
    agent_travel: "Zbyněk Phoibos",
    alamat: "2018/02/01",
    gambar: "Staff",
  },
  {
    id: 23,
    no: 1,
    agent_travel: "Aulus Agmundr",
    alamat: "2018/01/01",
    gambar: "Member",
  },
  {
    id: 42,
    no: 1,
    agent_travel: "Ford Prefect",
    alamat: "2001/05/25",
    gambar: "ddfd",
  },
];

export default data;
